In [1]:
import numpy as np
import pandas as pd
train = pd.read_csv('train.csv')
train.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [2]:
train=pd.read_csv('train.csv')
test=pd.read_csv('test.csv')
submit=pd.read_csv('submit.csv')

In [3]:
train.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [4]:
df=train.dropna() # Removing every missing value existing on the dataframe

In [5]:
X=df['title'] # Make Text column in Variable X
y=df['label'] # Make the labels on variable Y

In [6]:
# Firstly, fill all the null spaces with a space
train = train.fillna(' ')
train['total']=train['title'] + ' ' + train['author'] + ' ' + train['text']

In [7]:
print(train['total'])

0        House Dem Aide: We Didn’t Even See Comey’s Let...
1        FLYNN: Hillary Clinton, Big Woman on Campus - ...
2        Why the Truth Might Get You Fired Consortiumne...
3        15 Civilians Killed In Single US Airstrike Hav...
4        Iranian woman jailed for fictional unpublished...
                               ...                        
20795    Rapper T.I.: Trump a ’Poster Child For White S...
20796    N.F.L. Playoffs: Schedule, Matchups and Odds -...
20797    Macy’s Is Said to Receive Takeover Approach by...
20798    NATO, Russia To Hold Parallel Exercises In Bal...
20799    What Keeps the F-35 Alive David Swanson   Davi...
Name: total, Length: 20800, dtype: object


In [8]:
# cleaning our dataset 
import nltk 
from nltk.corpus import stopwords # to remove stop words such as ' the , they , it, a ...'
from nltk.stem import WordNetLemmatizer # for lemmatization task 
from nltk.tokenize import word_tokenize
from nltk.tokenize import wordpunct_tokenize


In [9]:
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package stopwords to C:\Users\This
[nltk_data]     PC\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to C:\Users\This
[nltk_data]     PC\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to C:\Users\This
[nltk_data]     PC\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


True

In [10]:
stop_words = stopwords.words('english')

In [11]:
word_data = "It originated from the idea that there are readers who prefer learning new skills from the comforts of their drawing rooms"
nltk_tokens = nltk.wordpunct_tokenize(word_data)
print(nltk_tokens)

['It', 'originated', 'from', 'the', 'idea', 'that', 'there', 'are', 'readers', 'who', 'prefer', 'learning', 'new', 'skills', 'from', 'the', 'comforts', 'of', 'their', 'drawing', 'rooms']


In [12]:
lemmatizer = WordNetLemmatizer()

In [13]:
pip install -U scikit-learn scipy matplotlib

     ---------------------------------------- 8.4/8.4 MB 1.7 MB/s eta 0:00:00
     ---------------------------------------- 42.5/42.5 MB 1.7 MB/s eta 0:00:00
     ---------------------------------------- 7.6/7.6 MB 2.7 MB/s eta 0:00:00
  Attempting uninstall: scipy
    Found existing installation: scipy 1.9.3
    Uninstalling scipy-1.9.3:
      Successfully uninstalled scipy-1.9.3
Note: you may need to restart the kernel to use updated packages.


ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Users\\This PC\\AppData\\Local\\Programs\\Python\\Python39\\Lib\\site-packages\\~cipy.libs\\libopenblas-57db09cfe174768fb409a6bb5a530d4c.dll'
Consider using the `--user` option or check the permissions.


[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [14]:
import re
for index, row in train.iterrows():
    filter_sentence = ''
    sentence = row['total']
    # Cleaning the sentence with regex
    sentence = re.sub(r'[^\w\s]', '', sentence)
    # Tokenization
    words = nltk.wordpunct_tokenize(sentence)
    # Stopwords removal
    words = [w for w in words if not w in stop_words]
    # Lemmatization
    for words in words:
        filter_sentence = filter_sentence  + ' ' +  str(lemmatizer.lemmatize(words)).lower()
    train.loc[index, 'total'] = filter_sentence
train = train[['total', 'label']]

In [15]:
X_train = train['total']
Y_train = train['label']

In [16]:
# this could take a while.
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
count_vectorizer = CountVectorizer()
count_vectorizer.fit_transform(X_train)
freq_term_matrix = count_vectorizer.transform(X_train)
tfidf = TfidfTransformer(norm = "l2")
tfidf.fit(freq_term_matrix)
tf_idf_matrix = tfidf.fit_transform(freq_term_matrix)

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(tf_idf_matrix,  Y_train, random_state=0)

In [18]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()
logreg.fit(X_train, y_train)
Accuracy = logreg.score(X_test, y_test)
print( 'LogisticRegression Accuracy :  ',Accuracy )

LogisticRegression Accuracy :   0.9615384615384616


In [19]:
from sklearn.naive_bayes import MultinomialNB
NB = MultinomialNB()
NB.fit(X_train, y_train)
Accuracy = NB.score(X_test, y_test)
print( 'Multinomial NB Accuracy :  ',Accuracy )

Multinomial NB Accuracy :   0.8442307692307692


In [20]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier()
clf.fit(X_train, y_train)
Accuracy = clf.score(X_test, y_test)
print( 'Decision Tree Accuracy :  ',Accuracy )

Decision Tree Accuracy :   0.9698076923076923


In [21]:
import tensorflow as tf # Import Latest tensorflow version 
tf.__version__

'2.11.0'

In [22]:
from tensorflow.keras.layers import Embedding, LSTM, Dense ## Neural networks layers 
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot # to encode the depending variable 
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [23]:
voc_size=5000 # max num words to take into consideration while training your model

In [24]:
X=[i.lower() for i in X] # lowercase each text 

In [25]:
onehot=[one_hot(words,voc_size) for words in X] 

In [26]:
sen_len=30
embedded_doc=pad_sequences(onehot, padding='pre', maxlen=sen_len) # pad sequence your texts
print(embedded_doc)

[[   0    0    0 ...  322 3138 2018]
 [   0    0    0 ...  254 1357 2620]
 [   0    0    0 ... 2429   26 1956]
 ...
 [   0    0    0 ...  978 4477 1327]
 [   0    0    0 ... 3358 2651 2259]
 [   0    0    0 ... 4588 2637 2464]]


In [27]:
embedding_vector_feature=40 
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_feature, input_length=sen_len))
model.add(LSTM(100))
model.add(Dense(1, activation='sigmoid'))
# sigmoid : to handle the output ( binary case )
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
# binary_crossentropy : because we have a binaray classification task 
# Adam : Stochastic gradient decenet optimizatiion 
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 30, 40)            200000    
                                                                 
 lstm (LSTM)                 (None, 100)               56400     
                                                                 
 dense (Dense)               (None, 1)                 101       
                                                                 
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [28]:
X_final=np.array(embedded_doc)
y_final=np.array(y)

In [29]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X_final, y_final, test_size=0.20, random_state=0)

In [31]:
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=10, batch_size=64)

Epoch 1/10
229/229 [==============================] - 22s 95ms/step - loss: 0.0084 - accuracy: 0.9976 - val_loss: 0.5053 - val_accuracy: 0.9215
Epoch 2/10
229/229 [==============================] - 23s 102ms/step - loss: 0.0050 - accuracy: 0.9986 - val_loss: 0.5346 - val_accuracy: 0.9169
Epoch 3/10
229/229 [==============================] - 23s 102ms/step - loss: 0.0040 - accuracy: 0.9986 - val_loss: 0.4917 - val_accuracy: 0.9221
Epoch 4/10
229/229 [==============================] - 22s 96ms/step - loss: 0.0041 - accuracy: 0.9988 - val_loss: 0.5026 - val_accuracy: 0.9150
Epoch 5/10
229/229 [==============================] - 22s 96ms/step - loss: 0.0030 - accuracy: 0.9993 - val_loss: 0.5626 - val_accuracy: 0.9259
Epoch 6/10
229/229 [==============================] - 29s 126ms/step - loss: 4.4943e-04 - accuracy: 1.0000 - val_loss: 0.6118 - val_accuracy: 0.9226
Epoch 7/10
229/229 [==============================] - 26s 114ms/step - loss: 1.0132e-04 - accuracy: 1.0000 - val_loss: 0.6555 - v